### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by stefanofalasca** [tijsverkoyen/HomeAssistant-FusionSolar#108]
Well seem that all data that I can see are only statistics data, missing all real time data. For example Status Battery %, battery energy in, bettery energy out, energy from grid, energy out to grid.....

<img width="247" alt="Screenshot 2023-08-30 alle 22 13 59" src="https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/1249181/9a5e66d6-b101-457d-bab6-85b4c1ed6192">

any idea ?

**Comment by tijsverkoyen** [comment]
The screenshot shows the plant data. 
The realtime data is linked to the inverter device.

**Comment by stefanofalasca** [comment]
I haven't any inverted devices showed, I see plant with this data

<img width="362" alt="Screenshot 2023-08-31 alle 21 26 36" src="https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/1249181/84f935c9-e575-4f06-80a0-b9dee255b157">

**Comment by tijsverkoyen** [comment]
There is something weird with your account.
Feel free to send your credentials to me ‘FusionSolar at verkoyen dot eu’ and I will try to debug it.

**Comment by stefanofalasca** [comment]
ok I sent you

**Comment by tijsverkoyen** [comment]
@stefanofalasca Yeah I tried to debug it. And I think the changes in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/109 will resolve your issues.

Do note that you will probably have performance issues in your Home Assistant instance on startup.

Could you try to apply the changes in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/109 and let me know if the issue is resolved. If so I will create a new release. Thanks in advance

As told by email you have access to more than 100 stations, which is not supported by the Huawei API. So you need to disable the stations that don't have meaning to you (as you already did). 
I still think it would be best that you contact your installer (or Huawei support) and tell them you have access to stations that are not yours, and they should limit your OpenAPI account to have acces to your station and devices only.

**Comment by stefanofalasca** [comment]
Thanks Tijs, I already opened a ticket to huwaei, before to try, I will try
soon
*Stefano Falasca*


Il giorno ven 1 set 2023 alle ore 16:04 Tijs Verkoyen <
***@***.***> ha scritto:

**Comment by stefanofalasca** [comment]
Now I see new devices : Inverter, Battery and Sensor Power. For Battery and
Sensor Power entities working, for Inverter no all entities are not
available
*Stefano Falasca*


Il giorno ven 1 set 2023 alle ore 18:05 Stefano Falasca ***@***.***>
ha scritto:

**Comment by stefanofalasca** [comment]
missing screenshot

*Stefano Falasca*


Il giorno ven 1 set 2023 alle ore 22:54 Stefano Falasca ***@***.***>
ha scritto:

**Comment by tijsverkoyen** [comment]
Did you restart? Is the device enabled?
Screenshot is still missing

**Comment by stefanofalasca** [comment]
yep work sorry, I restarted. Good work thanks
*Stefano Falasca*


Il giorno ven 1 set 2023 alle ore 23:08 Tijs Verkoyen <
***@***.***> ha scritto:

**Comment by stefanofalasca** [comment]
Tijs you know, which entities use to configure energy dashboard ? like
screenshot

*Stefano Falasca*


Il giorno ven 1 set 2023 alle ore 23:12 Stefano Falasca ***@***.***>
ha scritto:

**Comment by okidoki99** [comment]
Hello, i have also installed fusion solar, I only have 1 plant, but i'm missing one important sensor that should get me from the power sensor device the  grid consumption, also this sensor needs to be seen by the energy tab in HA in order to be able to see real energy usage. Or, change the type of the sensor.power_sensor_realtime_power to be seen in the energy dashboard as an individual device and in the electricity grid section from the energy setup page. Thanks!

**Comment by okidoki99** [comment]
If you are missing the data, from the API then I think a calculation needs to be done consumption_today - consumed from PV = consumed from grid. This is a no battery scenario.

**Comment by tijsverkoyen** [comment]
@okidoki99 i think this is a whole other issue. Feel free to create another issue.

 But I will not create calculations in this integration as I don’t believe this should be part of the integration. The data that Huawei exposes through their api is exposed. 
If you need to do calculations based on different entities, you can do so in Home Assistant.

**Comment by okidoki99** [comment]
I would do it but the data is not available, either the API does not return it or your config does not include it. It appears in the kiosk info on the web browser... maybe also Fusion Solar does not provide it.. don't know...
