### ISSUE TITLE
Realtime sensor - update interval

### ISSUE THREAD

**Issue by D-dc** [tijsverkoyen/HomeAssistant-FusionSolar#114]
Hi,

I am wondering if it is possible to somehow update the refresh interval specific for the realtime / active power entities specifically?
I notice all entities are updated every 5/6minutes by default which is definitely fine for most use-cases. However in order to do more advanced automations, it would be nice if certain entities could get updated more frequently.

I currently have just the station and the inverter as devices.

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/4463614/0dc7b6c4-c5c5-4966-acd8-60eee9b5633e)

Thanks!

**Comment by tijsverkoyen** [comment]
Hi. That is not possible due to the rate limiting restrictions for the Fusion Solar API. If you need realtime data you should look into the modbus integration. For instance: https://github.com/wlcrs/huawei_solarOn 29 Oct 2023, at 13:55, DDC ***@***.***> wrote:﻿
Hi,
I am wondering if it is possible to somehow update the refresh interval specific for the realtime / active power entities specifically?
I notice all entities are updated every 5/6minutes by default which is definitely fine for most use-cases. However in order to do more advanced automations, it would be nice if certain entities could get updated more frequently.
I currently have just the station and the inverter as devices.

Thanks!
