### ISSUE TITLE
Lifetime energy is no longer updating, while current day/month/year *are*

### ISSUE THREAD

**Issue by wimvanhooff-mtv** [tijsverkoyen/HomeAssistant-FusionSolar#132]
**Describe the bug**
The lifetime energy is only updating at start-up time, while the other entities are updating every few minutes.

** Debug information **

* Are you using Kiosk or Northbound / OpenAPI mode?
  * [ ] Kiosk
  * [x] Northbound OpenAPI
Since current day/month/year are working, credentials seem fine 

**To Reproduce**
Happens automatically

**Expected behavior**
Based on previous observations, I expect the lifetime energy to be updated every few minutes.

**Screenshots**

![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154081729/5af06122-1cb8-4d44-8316-0c9869c2a504)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154081729/cb2e8219-c07a-4302-b75f-7928223e544e)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154081729/fe1e7eb3-476e-4726-9850-5c4ecab0f705)
![image](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/154081729/fc34325e-2334-44bf-8380-91458dc55f64)

**Desktop (please complete the following information):**
 - OS: Docker on OpenMediaVault/Debian
 - Browser: Firefox
 - Version 121

**Additional context**
Running HA 2024.1

**Comment by wimvanhooff-mtv** [comment]
Downgrading to version 3.0.0 seems to have fixed the issue.
The logs point to energy_sensor.py being the culprit, which has this line 68 in version 3.0.0:

```if realtime_power == '0.00':```

... while in 3.0.1 this was changed to:

```if math.isclose(realtime_power, 0, abs_tol = 0.001):```

I'm guessing this should read:

```if math.isclose(float(realtime_power), 0, abs_tol = 0.001):```

**Comment by AndersHoglund** [comment]
Sorry, I can not duplicate this problem. Works fine here. Probably a Python version issue.
Leaving out optional named arguments should be fine, as per examples in the school book: 
[https://www.w3schools.com/python/ref_math_isclose.asp](url)

You can try open file energy_sensors.py and change line 68 from: 
`                if math.isclose(realtime_power, 0, abs_tol = 0.001):
`
to a variant with full set of optional argumentss:
`                if math.isclose(realtime_power, 0, rel_tol = 0, abs_tol = 0.001):
`
The later does not work here, the glitch reappears. I need to use something like this:
`                if math.isclose(realtime_power, 0, rel_tol = 0.001, abs_tol = 0.001):
`

However, it seems from the posted log that the problem may be named args,  as that Python version seems to expect a real number and not a str (arg name). If the above changes still does not work, try un-named args:
`                if math.isclose(realtime_power, 0, 0.001, 0.001):
`

Or try a weird mix of un-named and named args:
`                if math.isclose(realtime_power, 0, 0.001, abs_tol =0.001):
`
But none of those work here. both optional params must be named. The W3School site says the same if you try it.
`TypeError: isclose() takes exactly 2 positional arguments (4 given)`

All-in-all, I am lost. I am no Python coder, I give up.  
So, the only thing I can think of is: Make sure that all your System components are up to date. I use whatever comes in the Pi4 image, continuously updated. 

Also, the midnight glitch we are trying to filter out here is also visible in the one year and monthly energy data. This code only handles lifetime energy. Best solution is if Huawei could cleanup their act.

**Comment by AndersHoglund** [comment]
One more thought. I use the kiosk interface while this problem is reported using OpenAPI. What-if the realtime_power argument that is the culprit, not the tolerance args?? Log does not tell which arg has the str/real type mismatch. Are there some Python magic going on differently in the two Kiosk/OpenAPI branches, setting realtime_power to different types? Or maybe the Huawei responses look differently? 

Please insert a debug log statement before line 68, after the assignment of realtime_power, like: 
`                realtime_power = self.coordinator.data[self._data_name][ATTR_REALTIME_POWER]`
`                _LOGGER.debug(type(realtime_power))`

I can see that it is a float when data is coming from Kiosk:
2024-01-12 10:19:39.153 DEBUG (MainThread) [custom_components.fusion_solar.fusion_solar.energy_sensor] <class 'float'>  

And the fact it is a float was the root problem I tried to fix by using isclose(), the original code was comparing floats for equality and that is a major nono. If it turns out to be a string when using OpenAPI, that should be fixed elsewhere. Making sure both branches behave the same in this code common for both. Or a hard type cast here, like:
`                realtime_power = float(self.coordinator.data[self._data_name][ATTR_REALTIME_POWER])
`

**Comment by AndersHoglund** [comment]
@wimvanhooff-mtv I am so sorry, I did not read all your posts properly. You are probably correct in this part:

> I'm guessing this should read:
> if math.isclose(float(realtime_power), 0, abs_tol = 0.001):

Have you tried it? Did it work??
I have added this and it does not seem to do any harm, but I will see in an hour or so when the sun has set and power is zero if the statement works fully. I'll be back....

So the core problem is most likely that OpenAPI returns strings while Kiosk returns floats. Not too good, needs fixing.
@tijsverkoyen where can this be corrected? Can you fix it, please. Quick-fix is a type cast here, but a proper fix would be nice.

Sorry for all my rantings in prev. posts, it was too late at night (or rather too early in the morning) for reading and debugging.
/A

**Comment by AndersHoglund** [comment]
The float type cast does no harm to the Kiosk data, and the fix for the midnight glitch also works as usual. 

`2024-01-12 15:33:18.664 DEBUG (MainThread) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk] calculated API base url for JrlNJcLJ3daMl24aN4F45PIiLxw36xax: https://uni002eu5.fusionsolar.huawei.com
2024-01-12 15:33:18.664 DEBUG (MainThread) [custom_components.fusion_solar.sensor] fusion_solar
2024-01-12 15:33:18.665 DEBUG (MainThread) [custom_components.fusion_solar.sensor] JrlNJcLJ3daMl24aN4F45PIiLxw36xax
2024-01-12 15:33:18.956 DEBUG (SyncWorker_4) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] Received data for JrlNJcLJ3daMl24aN4F45PIiLxw36xax:
2024-01-12 15:33:18.956 DEBUG (SyncWorker_4) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] {'realTimePower': 0.048, 'cumulativeEnergy': 24661.57, 'monthEnergy': 16.02, 'dailyEnergy': 2.29, 'yearEnergy': 16.02}
2024-01-12 15:33:18.962 DEBUG (MainThread) [custom_components.fusion_solar.sensor] Finished fetching FusionSolarKiosk data in 0.298 seconds (success: True)
2024-01-12 15:43:18.663 DEBUG (MainThread) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk] calculated API base url for JrlNJcLJ3daMl24aN4F45PIiLxw36xax: https://uni002eu5.fusionsolar.huawei.com
2024-01-12 15:43:18.664 DEBUG (MainThread) [custom_components.fusion_solar.sensor] fusion_solar
2024-01-12 15:43:18.664 DEBUG (MainThread) [custom_components.fusion_solar.sensor] JrlNJcLJ3daMl24aN4F45PIiLxw36xax
2024-01-12 15:43:18.971 DEBUG (SyncWorker_5) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] Received data for JrlNJcLJ3daMl24aN4F45PIiLxw36xax:
2024-01-12 15:43:18.971 DEBUG (SyncWorker_5) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] {'realTimePower': 0.0, 'cumulativeEnergy': 24661.579999999998, 'monthEnergy': 16.03, 'dailyEnergy': 2.3, 'yearEnergy': 16.03}
2024-01-12 15:43:18.977 DEBUG (MainThread) [custom_components.fusion_solar.sensor] Finished fetching FusionSolarKiosk data in 0.313 seconds (success: True)
2024-01-12 15:43:18.978 INFO (MainThread) [custom_components.fusion_solar.fusion_solar.energy_sensor] sensor.kronkarrs_huawei_vr_jrlnjclj3daml24an4f45piilxw36xax_total_lifetime_energy: not producing any power, so no energy update to prevent glitches.`

Will PR this. Needs to be tested by some OpenAPI user.

**Comment by wimvanhooff-mtv** [comment]
Thanks for the help team!
Love the integration 🙂



Kind Regards, Vriendelijke Groeten,



Wim ***@***.***>  |  Montova platform expert  |  p: +32 (0)2 711 41 30  |  [MONTOVA] <https://www.montova.com/> , Belgicastraat 11 bus 4, BE-1930 Zaventem



________________________________
