### ISSUE TITLE
Debug log has state class total_increasing, but its state is not strictly

### ISSUE THREAD

**Issue by ward0** [tijsverkoyen/HomeAssistant-FusionSolar#197]
**Describe the bug**

2024-10-27 16:45:10.537 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.ward_coysman_total_current_day_energy from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 16.73 (16.76) with last_updated set to 2024-10-27T16:43:07.089449+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

** Debug information **
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant?: yes
* Are you using the latest version of this integration? yes
* Have you looked into the closed issues and did not find a similar issue. : yes
* Are you using Kiosk or Northbound / OpenAPI mode?: OpenAPI mode

**Comment by tijsverkoyen** [comment]
This is related to Huawei returning faulty data. I can't do anything about it.

**Comment by tielensjordi** [comment]
Hi,

We are also encountering the same warning message about the daily energy not being strictly increasing.

Could it be possible that Huawei is subtracting self-consumption from the total generated energy? This might explain why the sensor occasionally shows a decrease. I’ve also observed that Yield Today remains at 0.0 kWh for an unusually long time in the mornings, even when the PV system starts generating power.

Since the detection logic seems to me a part of Home Assistant Core and cannot be modified in the integration, would it be possible to adjust the sensor’s classification to one that supports non-strictly increasing values? This might better reflect the data behaviour without triggering unnecessary warnings.

What do you think about this approach?

Kind regards,
Jordi
